import jsPDF from 'jspdf';

export async function exportReportPdf({ sourceWallet, stats, attribution }) {
  const pdf = new jsPDF({ unit:'pt', format:'a4' });
  const left = 42;
  let y = 54;

  pdf.setFillColor(7, 11, 18);
  pdf.rect(0, 0, 595, 842, 'F');
  pdf.setTextColor(235, 239, 244);
  pdf.setFont('helvetica','bold');
  pdf.setFontSize(20);
  pdf.text('CryptoShield', left, y);
  y += 22;
  pdf.setFont('helvetica','normal');
  pdf.setFontSize(9);
  pdf.setTextColor(150, 160, 172);
  pdf.text('Fraud Investigation System · Prototype Report', left, y);
  y += 38;

  pdf.setTextColor(215, 221, 229);
  pdf.setFont('helvetica','bold');
  pdf.setFontSize(12);
  pdf.text('Investigation', left, y);
  y += 22;

  pdf.setFont('helvetica','normal');
  pdf.setFontSize(10);
  const rows = [
    ['Case ID', 'CASE-001'],
    ['Chain', 'Bitcoin'],
    ['Source wallet', sourceWallet || '—'],
    ['Wallets traced', String(stats.wallets)],
    ['Transfers', String(stats.transfers)],
    ['Transactions', String(stats.transactions)],
    ['Flagged wallets', String(stats.flagged)],
    ['VASP matches', String(stats.vasp)],
    ['Trace depth', String(stats.depth)],
    ['Risk score', 'Pending risk-engine output']
  ];

  for (const [label, value] of rows) {
    pdf.setTextColor(135, 147, 160);
    pdf.text(label, left, y);
    pdf.setTextColor(225, 230, 236);
    const text = String(value);
    const wrapped = pdf.splitTextToSize(text, 360);
    pdf.text(wrapped, 175, y);
    y += 24 + Math.max(0, wrapped.length - 1) * 11;
  }

  if (attribution) {
    y += 10;
    pdf.setTextColor(215, 221, 229);
    pdf.setFont('helvetica','bold');
    pdf.text('Selected Attribution', left, y);
    y += 22;
    pdf.setFont('helvetica','normal');
    pdf.setTextColor(145, 155, 168);
    pdf.text(`Entity: ${attribution.entity_type || 'wallet'}`, left, y); y += 18;
    pdf.text(`VASP: ${attribution.vasp_name || 'No match'}`, left, y); y += 18;
    pdf.text(`Confidence: ${((Number(attribution.confidence)||0)*100).toFixed(0)}%`, left, y);
  }

  y = 780;
  pdf.setFontSize(8);
  pdf.setTextColor(100, 110, 122);
  pdf.text('Generated by Person 4 frontend prototype. Risk values are not calculated by the frontend.', left, y);
  pdf.save('cryptoshield-investigation-report.pdf');
}
